# Generated by Django 3.1 on 2021-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_emp',
            field=models.BooleanField(default=False, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='manager'),
        ),
    ]
